[workspace]
resolver = "3"
members = ["tessera"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
repository = "https://github.com/theiskaa/tessera"

[workspace.dependencies]
tessera = { path = "tessera", default-features = true }
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
wasm-bindgen = "0.2"

[profile.release]
lto = "thin"
codegen-units = 1
